services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: "0:0"
    container_name: mateusmota-blog-dev
    command: >
      bash -c "bundle install && 
               bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling --future --drafts"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - "${PWD}:/srv/jekyll"
      - gem_cache:/usr/local/bundle
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development
    init: true

volumes:
  gem_cache: