FROM ruby:3.3-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m jekyll
USER jekyll

WORKDIR /srv/jekyll

RUN gem install bundler